stellar/freighter-backend

package.json, src/helper/test-helper.ts, src/helper/validate.ts, src/route/index.ts, src/route/validators.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts, src/stub.test.ts, yarn.lock
Adds new Mercury service calls to build a token balance key, and to subscribe to token balances.
New Route:
GET `/account-balances/:pub-key`
POST `/subscription/token-balance`
Adds customer validator to check that arguments can resolve to contract addresses, `isContractId`.
Todo:
Mercury is currently working on adding classic asset balances to full account subscriptions, once that feature is live then we can add the query to fetch balances to `MercuryService.getAccountBalances`
=> [FEAT] adds call and route to index token account balance

README.md, src/helper/test-helper.ts, src/index.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts
Allows 401 handling by renewing the user jwt, and retrying the underlying call again.
Changes -
Adds `renewAndRetry` to MercuryService in order to enable 401 handling.
Wraps all MercuryService methods with a `renewAndRetry`.
=> Adds renewAndRetry to all mercury service methods

src/config.ts, src/service/mercury/helpers/transformers.ts
Tweaks config to allow for setting env vars directly, they override an env file or replace one if one is not found.
=> adds support for env vars if env file is not found

src/helper/format.ts, src/helper/horizon-rpc.ts, src/helper/soroban-rpc.ts, src/helper/test-helper.ts, src/helper/validate.ts, src/route/index.test.ts, src/route/index.ts, src/service/mercury/helpers/transformers.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts
Adds new classic ops recently added to Mercury.
This adds the remaining classic side ops queries to be used for account history routes.
Also fixes a few small query bugs found during testing.
Adds fallback to Horizon and transformer.
Notes -
This completes the queries needed for data parity with Horizon/Soroban RPC.
=> Adds newly supported classic ops, tweaks route and query for history

src/helper/soroban-rpc.ts, src/route/index.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts
Ticket: https://stellarorg.atlassian.net/jira/software/c/projects/WAL/boards/36?assignee=63bc81730a1b5442166a2f79&selectedIssue=WAL-1212
In order to support custom networks in Freighter, we need to be able to optionally pass RPC URLs to be used for account balances and account history.
This adds optional query params on both routes to provide those, and updates the service to attempt to use those URLs in the case that we don't have a match for natively supported URLs.
=> adds options for custom rpc urls

src/helper/horizon-rpc.ts, src/route/index.ts, src/service/mercury/index.ts
The platform team would like Freighter to start moving towards a world where it doesn't use the RPCs directly in an effort to move away from promoting the SDF hosted RPCs and to encourage community involvement.
This adds a way to submit transactions to the RPC through a route, submitting transactions to the Horizon RPC should work for Soroban(invoke host fn) ops as well.
=> adds route and helper to submit transaction to the horizon rpc

.env-EXAMPLE, src/config.ts, src/helper/test-helper.ts, src/index.ts, src/route/index.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts
This will allow us to toggle Mercury off globally if needed, initially to be prepared for the deployment to prd in the case that we are not ready on the Mercury side.
=> add env var toggle to turn off mercury globally

src/service/mercury/index.ts
Fixes this: https://stellarorg.atlassian.net/browse/WAL-1228 along with https://github.com/stellar/freighter/pull/1077
This fixes an oversight in history for cases where the network supports Horizon but not Soroban RPC.
This is only pubnet and will soon be no networks, expect maybe standalone networks where Soroban RPC is turned off.
I think there's still an open question of what we should do if one of the RPCs errors and the other doesn't, this doesn't seem likely but it's possible. Right now, we try for a composite data/error flow, where we return data from either if we can while logging errors from either but maybe it would be better to surface the errors from either even if we have a successful response from the other and let the client handle how to surface that to the user?
=> [FIX] Fallback history for networks that support Horizon but not Soroban RPC

src/route/metrics.ts
This was previously not returning the metrics data, but an empty success response.
=> [BUG] fixes dropped metrics data

src/helper/horizon-rpc.ts, src/helper/soroban-rpc.ts, src/route/index.test.ts, src/route/index.ts, src/route/validators.ts, src/service/mercury/helpers/transformers.ts
This is needed to fix the token payment flow in the client, now prepares tx in token simulation request lifecycle.
=> prepares tx in token simulation flow

src/helper/error.ts, src/helper/horizon-rpc.ts, src/route/index.ts, src/service/mercury/index.ts
Adds checks during token simulation to attempt to constrain simulation to a typical transfer implementation.
=> Constrain token payment by auth entries

src/config.ts, src/route/index.ts
Passes through `server.getHealth` so that we can check on rpc connection status from a route.
=> adds a route to pass through rpc health

src/helper/horizon-rpc.ts, src/route/index.ts, src/service/mercury/index.ts
What
Adds 2 new route -
`/user-subscription`
`/horizon-health`
Why
`/user-subscription`
This route will be used to trigger generic notification to show in the UI. Since the deployment lifecycle for the backend is much faster than the client, we can use this as an mvp notification system by deploying a change that toggles the `enabled` flag to true, and sets a string to be displayed in the UI.
`/horizon-health`
This route will be used in order to trigger a Horizon related degradation notice. Notable the Horizon health endpoint is different from the rpc one in that the rpc one looks to be about describing the health of the rpc itself and the Horizon one looks to be used to provide health checks for it's dependencies like it;s database and core instance. The response looks like this …
=> [FEATURE] Feature/new routes health and generic message

src/helper/soroban-rpc.ts, src/route/index.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts
What
Removes custom RPC URLs from routes and service
Why
We no longer support custom RPC in the backend, client uses this client side now.
=> [CHORE] Remove custom RPC URLs from routes & service

src/helper/error.ts, src/helper/mercury.ts, src/helper/test-helper.ts, src/service/mercury/helpers/transformers.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts
What
Adds `getAccountSubForPubKey` that checks if a public key has an account subscription in Mercury.
Uses this check in `getAccountHistoryMercury` & `getAccountBalancesMercury`
Why
To guard us against failed subscriptions or otherwise missing subscriptions for account that we try to query Mercury for, falls back to RPCs if the public key has no account subscription.
=> [FEATURE] Check subscription before query

src/config.ts
What
Refactors the config env variable check to not reject unknown keys, and to reject on missing ones
Why
This was previously rejecting unknown keys which is not needed since we will ignore them anyways, and that behavior will crash the server if we ever remove an env var and dont remove it in our infra setup.
=> fixes check in config to not reject on unknown keys

src/helper/soroban-rpc.ts, src/route/index.ts, src/service/mercury/index.ts
What
Passes simulation failures through to the caller, and returns those in the route response error case for token-details
Why
Errors from token-details were not very helpful for clients, didn't expose failure reasons
=> [FIX] pass simulation failures as error message in route response

src/service/mercury/index.test.ts, src/service/mercury/index.ts
What
Adds `retryCount` optional param to `renewAndRetry`. This allows callers to add a number of retries to do in case of a non 401 error response.
Uses `retryCount` in subscriptions to retry failure cases.
Refactors and adds tests for `renewAndRetry`.
Why
In the edge case that we fail a subscription, we should retry a low number of times in order to guard against transient errors.
=> [FEATURE] Retry on non 401 subscription errors

src/config.ts, src/helper/soroban-rpc/index.ts, src/helper/test-helper.ts, src/index.ts, src/service/mercury/helpers/transformers.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts
What
Implements a new API from Mercury that keeps track of the most recent data for trustlines and contract entries without the need for a subscription, uses this API in `getAccountBalance`
Why
Mercury added the "current data API" which gives access to latest values for trustline balances and contract entries(token balances) without setting up a subscription. Using the current data API we can build the view of data that we need for account balances without having to rely on/check subscriptions. This should result in faster queries against Mercury for account balances.
=> [FEATURE] current data api

src/helper/test-helper.ts, src/service/mercury/helpers/transformers.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts, src/service/mercury/queries.ts
What
Adds account object query from the current data API, replaces use of account object query from the subscription based API
Why
This data is available in the current data API and will significantly improve our query performance on the account balances queries through Mercury
=> [FEATURE] adds account object query to current data api, replaces subscription

src/service/mercury/helpers/transformers.ts
What
Adds `minimumBalance` key to Mercury account object transformer
Fixes the calc for `available`
Why
Horizon returns a `minimumBalance` key which is unused by the UI right now but this will now match the Horizon response more closely
`available` field was being calculated as the `minimumBalance`, unused in the UI but this fixes that discrepancy.
=> [FIX] account object extra fields

src/config.ts
What
Fixes config check to allow vars set directly in env and not loaded through .env files
Why
This check was incorrectly failing in CI because we use a combo of env vars and .env file vars there.
=> fixes config check to include vars set in shell

src/helper/soroban-rpc/index.ts, src/route/index.ts
What
Adds getContractSpec route
Why
For use during transaction signing to expose more detail about contract spec.
=> adds getContractSpec route

src/helper/metrics.ts, src/helper/test/metrics.test.ts, src/route/index.ts
What
Fixes the cardinality problem in the `http_request_duration_s` metric
Adds network label
Why
Each route slug and param was being tracked as it's own label, exploding the cardinality of this metric type.
=> [BUG] Fix metric cardinality for http_request_duration_s

src/helper/fetch.ts, src/helper/mercury.ts, src/helper/metrics.ts, src/index.ts, src/service/integrity-checker/worker.ts, webpack.prod.js
What
Adds worker module and moves integrity check to run in worker thread
Moves common helpers to helper files
Why
This will help keep the main thread clear for API usage while the integrity check runs in worker thread
=> [FEATURE] Integrity check runs in worker

.github/dependabot.yml
Adding base config for `dependabot.yml`, which enables automatic PRs for [dependency version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) through Dependabot. This base config sets version updates to run on a `weekly` schedule, groups PRs for version updates according to `major` vs `minor/patch` updates, and sets max PRs that Dependabot can create for version updates per package-ecosystem. 
But if you would like, several config options can be added to `dependabot.yml` as per [configuration-options-for-the-dependabot.yml-file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to customize version updates, such as:
- Group PRs for …
=> Add dependabot.yml for dependency version updates

package.json, src/helper/error.ts, src/route/index.ts, src/service/blockaid/index.ts, yarn.lock
What
Adds blockaid tx scanning and validation
Why
To be used in Freighter when a user signs a tx
Docs: https://docs.blockaid.io/reference/scan_transaction_scan_transaction_post
=> [FEATURE] adds blockaid scan tx service method and route

src/helper/mercury.ts, src/service/integrity-checker/worker.ts
What
Makes timeouts optional in the GraqhQL client makers.
Turns timeouts off for clients used during integrity checks.
Why
These timeouts were occasionally triggering a timeout during integrity checks when we get unlucky and hit an account that has a huge number of ops.
In practice, we don't care about the integrity checks resolving in under 5s or any reasonable amount of time as long as they resolve. We still use timeouts for clients used when serving user requests.
=> [FEATURE] Optional timeout in gql client construction

package.json, src/route/index.test.ts, src/service/blockaid/helpers/addScanResults.ts, src/service/blockaid/index.ts, yarn.lock
_What_
The Blockaid team has added the bulk asset scan endpoint to their SDK.
_Why_
This now uses 1 API request for all the assets a users has rather than O(n)
=> refactor addScanResults to use bulk scan

src/route/index.ts
What
Removes contract_ids as required query param, it is optional
Why
Accidentally made required during earlier work
=> removes contract_ids from required keys on account balance route

src/route/index.test.ts, src/route/index.ts
This route will be useful for users who are on Mainnet, but on a custom network (like with a custom RPC). This will allow us to still validate the user's assets even thought they're not grabbing their balances from our BE
=> add route to bulk scan assets

src/route/index.ts
What
The catch for the blockaid scan part of this route flow did not properly set the base response with a `blockaidData` key for each balance.
Why
In the case of an error scanning through blockaid, the response shape returned is different from the expected response by clients.
=> [BUG] error case account balances scan

src/helper/test-helper.ts, src/route/index.test.ts, src/route/index.ts, src/service/mercury/helpers/transformers.ts, src/service/mercury/index.test.ts, src/service/mercury/index.ts
Related: https://github.com/orgs/stellar/projects/58/views/2?pane=issue&itemId=80122477&issue=stellar%7Cfreighter%7C1646
Given the new ["Add Token" API](https://github.com/stellar/freighter/pull/1815) we are implementing on freighter's extension we'll need to return the token balance along with its other details in order to display it on the popup's UI (see [comments](https://github.com/stellar/freighter/pull/1815#discussion_r1941714567)) so users are aware of the new balance info.
=> Allow optional "fetch_balance" parameter on /token-details route

src/route/index.test.ts, src/service/mercury/index.ts
Related: https://github.com/stellar/freighter-backend/pull/204
This PR makes sure to cache only the static token details, and when the balance is requested (`should_fetch_balance=true`) it should always fetch the latest balance amount but still fetch and merge the cached static token details if any to make the request more performant.
=> Only use cache for static token details

src/route/index.ts, src/service/prices/index.test.ts, src/service/prices/index.ts
This fixes a bug where we fail to add new tokens to cache because we are not able to find any paths to calculate new prices for them
=> Handle case where price is not calculated for new token

src/config.ts, src/helper/soroban-rpc/index.test.ts, src/helper/soroban-rpc/network.ts, src/helper/soroban-rpc/token.ts, src/helper/test-helper.ts, src/index.ts, src/route/index.test.ts, src/route/index.ts, src/service/integrity-checker/worker.ts, src/service/mercury/index.ts
Closes #238 
- Add functionality to pass RPC URLs for different networks as env variables.
- Use the public URLs for testnet and futurenet as default value, if not passed by user.
- Throw error if requested network is public but no URL is set by user.
- We currently hardcode the production kube cluster URL which is not a good practice.
- With our new dev and prd namespaces running their own RPC pods, we should use those URLs encoded as kube secrets for the respective freighter backend pods to connect to.
=> Pass RPC URLs as env variables

src/config.ts, src/service/prices/index.test.ts, src/service/prices/index.ts
- Use [TS.REVRANGE](https://redis.io/docs/latest/commands/ts.revrange/) to get the approx price 24h ago.
- Add ability to specify the 24h threshold via an environment variable.
We currently store the token prices in a redis timeseries structure with a retention policy of 24h. On each request for a token we fetch the latest price and the 24h price and then calculate the 24hr % change.
The idea was to check for prices within the timestamp range = [timestamp at (24h-1min), timestamp at 24h] and get the price that falls in this interval. However, with the increase in the number of tokens in the cache, the batch updates between prices increased and the probability of finding a price within this hardcoded 1 min time interval reduced. This led to the client not able to find 24h price sometimes …
=> Use revRange for calculating 24h price change

src/route/index.test.ts, src/route/index.ts
Closes #1963
Adds a POST method to scan-tx endpoint that will eventually replace the GET method. This will fix our issue with char limits
=> Change scan tx to post

src/helper/horizon-rpc.ts, src/helper/test-helper.ts, src/route/index.test.ts, src/route/index.ts, src/service/mercury/index.ts
Related to [Freighter #1844](https://github.com/stellar/freighter/issues/1844)
Parameterize account-history to only include failed tx's for Freighter users who have upgraded
=> add query param to toggle including failed tx's

src/helper/metrics.ts, src/helper/test/metrics.test.ts
This will label all non-whitelisted spam URLs as "other" and avoid the metrics explosion in prometheus
=> [DO NOT MERGE YET] Add route whitelisting for prometheus metrics
