stellar/freighter-backend

src/service/mercury/queries.ts

Adds new classic ops - 
path payments strict receive
path payments strict send
manage sell offer
manage buy offer
passive sell offer
change trust

Adds new batch of classic ops to account history query

---

package.json
src/helper/soroban-rpc.ts
src/helper/test-helper.ts
src/route/index.test.ts
src/route/index.ts
src/service/mercury/helpers/transformers.ts
src/service/mercury/index.test.ts
src/service/mercury/index.ts
src/service/mercury/queries.ts
yarn.lock

A few tweaks after the protocol upgrade.
- Tweak to entry sub API, Mercury update
- Remove extra log found in service
- upgrades to newest stellar-sdk

updates the sdk, and tweaks logic for protocol upgrade

---

package.json
src/helper/test-helper.ts
src/index.ts
src/route/index.ts
src/service/mercury/index.ts
yarn.lock

Adds cors for the remote endpoint
https://stellarorg.atlassian.net/browse/WAL-1227

Adds cors open to all origins

---

src/route/index.ts

This aligns the response from 400 level errors to be JSON strings.

json stringifies all errors returned from router

---

src/helper/test-helper.ts
src/index.ts
src/route/index.ts
src/route/metrics.ts

adds separate metrics server to serve metrics on separate port

---

src/helper/test-helper.ts
src/index.ts
src/route/index.test.ts
src/route/index.ts
src/service/mercury/index.ts

Adds route based counters and response times.

adds route based http metrics

---

src/helper/soroban-rpc.ts
src/service/mercury/index.ts

Adds Futurenet RPC in Soroban RPC map, uses it in account balance call.

[BUG] Adds Futurenet RPC URL to account balance

---

CHANGELOG.md
package.json
src/config.ts
src/helper/soroban-rpc.ts
src/helper/test-helper.ts
src/index.ts
src/route/index.ts

Adds Soroban RPC URL for pubnet
Adds toggle to control support for Soroban pubnet
Adds first changelog entry

Soroban support for Pubnet

---

src/route/index.ts
src/service/mercury/index.ts

What
Updates getAccountBalance to return a composite response from Horizon and Soroban calls.
Why
In order to give clients as much data as possible when one source fails.

[FEATURE] getAccountBalance composite response

---

src/service/mercury/index.test.ts
src/service/mercury/index.ts

*What*
- When fetching a SAC balance from Soroban RPC, don't include it in the final balance object
*Why*
- Because SAC balances can be retrieved from both Horizon and a Soroban RPC, one SAC ends up with 2 balances. Let'a just use the Horizon balance as this allows us to get the asset icon a bit easier

de dupe SAC balances

---

package.json
src/helper/horizon-rpc.ts
src/helper/soroban-rpc/index.test.ts
src/helper/soroban-rpc/index.ts
src/route/index.ts
src/service/mercury/helpers/transformers.ts
src/service/mercury/index.ts
yarn.lock

What
Upgrades to stellar-sdk v12.0.0 rc1, includes support for p21
Why
P21 is in futurenet

upgrade stellar-sdk to 12.0.0 rc 1 for futurenet

---

src/index.ts

use default connection timeout

---

src/config.ts
src/service/mercury/queries.ts

What
Updates Mercury URLs for new schema
Why
Mercury is moving to new schemas, will deprecate old URLs

[CHORE] updates Mercury URLs for their new URL schema

---

src/helper/metrics.ts

Use url instead of method for route label

[BUG] use url instead of method for route label

---

src/service/mercury/helpers/transformers.ts
src/service/mercury/queries.ts

What
Updates schema for new Mercury changes

[FEATURE] adapt to new mercury schema

---

src/helper/metrics.ts
src/index.ts
src/service/integrity-checker/index.ts
src/service/integrity-checker/worker.ts

What
Uses thread message passing to increment integrity check counters
Why
Metrics were not being logged to register due to increment happening in the worker thread.

[BUG] Fix/metrics thread message

---

src/helper/metrics.ts
src/index.ts
src/service/integrity-checker/index.ts

* correctly imports sentry and fixes metrics register
* uses thread message passing to inc integrity check counters
* remove counters from service construction

[BUG] Fix/metrics thread message (#96)

---

src/index.ts
src/service/integrity-checker/index.ts
src/service/integrity-checker/worker.ts

What
Inits Sentry from the worker thread in order to use it in the integrity check

inits Sentry from worker for usage in worker thread integrity check

---

src/index.ts
src/service/integrity-checker/index.ts
src/service/integrity-checker/worker.ts

What
Temporary debug logs for remote instance

adds debug logs for integrity check alerts

---

src/logger.ts

What
Redacts logs of headers and params that include potential PII

[FEATURE] Redact logs

---

src/route/index.ts

What
Improves schema validation for query params/body.
Why
Omitting some params will return 500s in some cases due to validation not requiring the params, this makes the responses more appropriate as 400 level responses.

[FEATURE] Improve schema validation

---

package.json
src/service/blockaid/index.ts
yarn.lock

Upgrading blockaid scanning tx to use the single tx scanning method

upgrade blockaid to use single tx scanning

---

package.json
src/route/index.test.ts
src/service/blockaid/helpers/addScanResults.ts
yarn.lock

When retrieving balances, include all the data we get back from Blockaid to display in the UI

upgrade blockaid/client and return full blockaid results

---

README.md
docs/runbook.md

What
Adds runbook and updates README
Why
Adds missing documentation for runtime config/testing/monitoring

[CHORE] adds runbook and updates readme

---

README.md
docs/mercury.md

What
Adds docs on Mercury's integration

[CHORE] adds a mercury integration guide

---

package.json
src/config.ts
src/helper/error.ts
src/helper/test-helper.ts
src/route/index.test.ts
src/route/index.ts
src/service/blockaid/index.ts
yarn.lock

* Adding endpoints to report incorrect asset warnings
* Adding endpoints to report incorrect transaction warnings
* Add config to disable above endpoints, similar to other Blockaid endpoints

add Blockaid reporting endpoints

---

src/route/index.test.ts

There was a leftover `.only` call that allowed failing tests to be merged in previous PRs. This removes that call and fixe the broken tests.

[FIX] Fixes broken unit tests

---

src/route/index.ts
src/service/prices/index.test.ts
src/service/prices/index.ts
src/service/prices/worker.ts

- Add a retry mechanism to restart price worker.
- Expose an endpoint for health check of the price worker

Add retry mechanism if price worker gets terminated with an exit code or error

---

package.json
src/helper/soroban-rpc/network.ts
src/helper/soroban-rpc/token.ts
src/route/index.test.ts
src/route/index.ts
yarn.lock

#252 
Correctly sets `allow-http` flag in transaction simulation route

Release 1.8.0

---

src/route/index.ts

Adds a log for request IP and proxy IPs

[DEBUG] adds a debug log for request IP

---

package.json
src/config.ts
src/helper/test-helper.ts
src/index.ts
src/route/index.ts
yarn.lock

Adds option to trust proxy IP from env

adds env var for proxy range and uses it to config req ip

---

src/route/index.ts

Removes the IP debug log, no longer needed after confirmation.

[CHORE] removes IP debug log
